# Short-term stocks
short_term:
  stocks: [
    BIRD,
    DNA,
    STRYQ,
  ]
  # Window and number of std dev for Bollinger Bands
  window: 10
  num_stdev: 1.75

# Long-term stocks
long_term:
  stocks: [
    AAPL,
    AMC,
    AMZN,
    AXP,
    BAC,
    BUD,
    BYND,
    CMCSA,
    DIS,
    DVN, # div
    HD,
    GE,
    GME,
    GOGO,
    GOOG,
    INTC,
    JNJ,
    LGVN,
    MRNA,
    MSFT,
    NKE,
    NVDA,
    OXY,
    PFE,
    PLL,
    PLTR,
    RIVN,
    ROKU,
    SBUX,
    SLB,
    SNOW,
    T, # div
    TDOC,
    TSLA,
    VOO,
    VRTX,
    VTRS,
    ZM]
  window: 20
  num_stdev: 2
