# File with info about owned stocks
filename: 'config/Portfolio_Positions.csv'

# Stock categories for email 
buy_list: [['TSLA', 1200, -15],
           ['PLL', 75, -10]]  # stocks to buy, with target sell price, and desired % profit (e.g. buy PLL when ~$68)
additional: ['INTC']  # stocks to track so can categorize later

# Stock categories for Streamlit app
long_term: ['SLB']  # stocks to keep long-term
short_term: ['PLTR']  # stocks to keep short-term (buy when there's a dip)
buy_asap: ['BAC']  # stocks to buy immediately when there is a dip
sell_asap: ['ZM']  # stocks to seel immediately when there is a bump

# Additional params 
update: False  # whether or not to send email update outside of beginning and end of day
threads: 5  # number of threads for webscraping
margin: -4  # % change for which to send automatic alerts

# 1) price dips below X% (margin) of previous close
# 2) price dips below X% (margin) of price at which stock was bought

# Email info (obtain from google API)
GOOGLE_ACCOUNTS_BASE_URL: 'https://accounts.google.com'
GOOGLE_CLIENT_ID: ''  # Gmail variables and tokens
GOOGLE_CLIENT_SECRET: ''
GOOGLE_REFRESH_TOKEN: ''
    
# Emails
username: ''
toaddr: ''
